version: '3.8'

services:
  manejador_reportes:
    build: ./manejador_reportes
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: always

  email_worker:
    build: ./workers
    env_file:
      - .env
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_choco
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: choco_reportes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: