version: '3.8'

services:
  manejador_reportes:
    build: ./manejador_reportes
    ports:
      - "8000:8001"
    env_file:
      - .env
    restart: always

  email_worker:
    build: ./workers
    env_file:
      - .env
    restart: always
