version: '3.8'

services:
  services:
  manejador_reportes:
    build: ./manejador_reportes
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASS=${RABBIT_PASS}
    restart: always

  email_worker:
    build: ./workers
    environment:
      - RABBIT_HOST=${RABBITMQ_HOST}
