# Generated by Django 4.2 on 2026-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.IntegerField()),
                ('id_area', models.IntegerField()),
                ('id_proyecto', models.IntegerField()),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=4, max_digits=14)),
                ('moneda', models.CharField(max_length=3)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consumos',
            },
        ),
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.IntegerField()),
                ('id_area', models.IntegerField()),
                ('id_proyecto', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('moneda', models.CharField(max_length=3)),
                ('costo_total', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('cantidad_registros', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'resumenes',
            },
        ),
        migrations.AddIndex(
            model_name='resumenmensual',
            index=models.Index(fields=['id_proyecto', 'anio', 'mes'], name='resumenes_id_proy_4641ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resumenmensual',
            unique_together={('id_empresa', 'id_area', 'id_proyecto', 'anio', 'mes')},
        ),
        migrations.AddIndex(
            model_name='consumo',
            index=models.Index(fields=['id_proyecto', 'anio', 'mes'], name='consumos_id_proy_6ed8c5_idx'),
        ),
    ]
