-- Tabla de auditoría
CREATE TABLE audit_logs (
    id SERIAL PRIMARY KEY,
    user_id TEXT,
    role TEXT,
    action TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--BLOQUEAR UPDATE
CREATE OR REPLACE FUNCTION prevent_update()
RETURNS trigger AS $$
BEGIN
   RAISE EXCEPTION 'UPDATE NOT ALLOWED ON AUDIT LOGS';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER no_update
BEFORE UPDATE ON audit_logs
FOR EACH ROW
EXECUTE FUNCTION prevent_update();

-- BLOQUEAR DELETE
CREATE OR REPLACE FUNCTION prevent_delete()
RETURNS trigger AS $$
BEGIN
   RAISE EXCEPTION 'DELETE NOT ALLOWED ON AUDIT LOGS';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER no_delete
BEFORE DELETE ON audit_logs
FOR EACH ROW
EXECUTE FUNCTION prevent_delete();

--EXTRA (CLAVE)
REVOKE UPDATE, DELETE, TRUNCATE ON audit_logs FROM PUBLIC;